In [1]:
import numpy as np

In [2]:
s = [1,2,3,4]
print(type(s))

t = np.array(s)
print(t)
print(type(t))
print(t.dtype)   # datatype of the element contained in array

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [3]:
my_matrix = [[5,55,555],[6,66,666],[7,77,777],[8,88,888]]
type(my_matrix)
my_matrix

[[5, 55, 555], [6, 66, 666], [7, 77, 777], [8, 88, 888]]

In [4]:
np.array(my_matrix)

array([[  5,  55, 555],
       [  6,  66, 666],
       [  7,  77, 777],
       [  8,  88, 888]])

In [5]:
np.arange(50)   # it will create an array from 0 to 50-1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
print(np.arange(100,151,2))# For Simple Skipping of the elements
np.arange(151,100,-1)# For Reverse Order

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150]


array([151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139,
       138, 137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126,
       125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113,
       112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101])

# zeros and ones

In [7]:
np.zeros((7,8))     # it will create a matrix contain zeros only , with 7 rows and 8 columns

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.zeros((7,8),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
np.ones((5,5))# it will create a matrix contain ones only , with 5 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((5,5),dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# eye

In [11]:
np.eye(3,4) # it will create an identity matrix with 3 rows and 4 columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
np.eye(5,5,dtype=int) * 3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

# rand 

In [13]:
np.random.rand(3,3) # create an array of 5 rows and 5 columns from a uniform distribution over [0,1)

array([[0.50951961, 0.91225615, 0.116331  ],
       [0.95541203, 0.64147019, 0.38250286],
       [0.92685904, 0.74691289, 0.90186792]])

In [14]:
np.random.rand(7,2,3)#(Number of individual matrixes,number of rows,number of columns)

array([[[0.63904612, 0.2446753 , 0.8234836 ],
        [0.88574638, 0.84082641, 0.51774171]],

       [[0.79924765, 0.51937635, 0.46040867],
        [0.64304613, 0.30463647, 0.75808461]],

       [[0.74587311, 0.62800729, 0.61421621],
        [0.83706626, 0.99525224, 0.29971493]],

       [[0.13418449, 0.07274348, 0.9460755 ],
        [0.74327263, 0.73620613, 0.17544017]],

       [[0.77373102, 0.67016356, 0.90540266],
        [0.23912337, 0.82461565, 0.08808926]],

       [[0.17531913, 0.47093872, 0.63568159],
        [0.22394823, 0.83534662, 0.91341471]],

       [[0.86599444, 0.10926704, 0.12145611],
        [0.40346044, 0.74631785, 0.15829411]]])

# randint

In [15]:
np.random.randint(10,21)

16

In [16]:
np.random.randint(50,70,size = (12,5))

array([[50, 58, 65, 53, 62],
       [52, 54, 66, 57, 59],
       [65, 68, 56, 51, 53],
       [67, 65, 53, 69, 54],
       [64, 50, 54, 62, 64],
       [57, 67, 61, 52, 58],
       [66, 69, 54, 58, 59],
       [51, 59, 57, 62, 59],
       [57, 57, 51, 57, 67],
       [56, 68, 66, 57, 56],
       [50, 61, 69, 64, 65],
       [54, 59, 51, 57, 52]])

In [17]:
np.random.randint(10,21,(5,5))

array([[15, 20, 12, 15, 16],
       [15, 10, 18, 20, 20],
       [10, 15, 11, 20, 18],
       [18, 20, 13, 11, 15],
       [10, 16, 18, 12, 16]])

In [18]:
np.random.randint(50,70)

55

In [19]:
np.random.randint(50,70,25)

array([50, 58, 54, 52, 66, 67, 54, 54, 56, 65, 62, 55, 69, 59, 60, 66, 50,
       52, 51, 60, 56, 52, 66, 55, 59])

In [20]:
np.random.randint(1,100,25)

array([26, 92,  1, 92, 50, 42, 41, 15, 75,  2, 58, 79, 95, 28, 13, 22, 32,
       74, 92, 70, 10, 85, 65,  6, 26])

# Array Attributes and Methods

In [21]:
arr = np.arange(1,26)
ranarr = np.random.randint(50,100,25)
print(ranarr,"Ranarr - RandInt")
print()
print(arr,"Arr - Arange")

[72 82 74 74 92 50 69 80 58 60 61 55 77 83 94 56 81 71 56 55 91 93 51 53
 79] Ranarr - RandInt

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] Arr - Arange


In [22]:
print(arr.shape,ranarr.shape)

(25,) (25,)


In [23]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
gun = ranarr.reshape(1,25)
gun

array([[72, 82, 74, 74, 92, 50, 69, 80, 58, 60, 61, 55, 77, 83, 94, 56,
        81, 71, 56, 55, 91, 93, 51, 53, 79]])

In [25]:
gun.reshape(5,5)

array([[72, 82, 74, 74, 92],
       [50, 69, 80, 58, 60],
       [61, 55, 77, 83, 94],
       [56, 81, 71, 56, 55],
       [91, 93, 51, 53, 79]])

In [26]:
ranarr = np.random.randint(50,100,25).reshape(5,5)   #(start, end, no. of elements)
ranarr

array([[87, 81, 91, 66, 78],
       [89, 62, 82, 74, 60],
       [98, 85, 90, 97, 86],
       [76, 85, 85, 76, 84],
       [70, 77, 87, 51, 51]])

In [27]:
print(ranarr.min())
ranarr.max()

51


98

In [28]:
print(ranarr.argmax()) # prints the index position of maximum number
ranarr.argmin() # prints the index position of minimum number

10


23

In [29]:
x1=["Hello"]
x2="Good Morning"
x3=[123]
x4=123
x5={"a":[55,67,89]}
x6={1,2,3}
x7=np.array([1,2,3,4,5,6,7,8])
x8=np.array(["Hello","Good Morning"])

In [30]:
print(type(x7))
x8.dtype

<class 'numpy.ndarray'>


dtype('<U12')

In [31]:
type(x5)
type(arr)
#Basic Difference between type() and .dtype.
#type() function runs with any data type and it also works with numpy/array objects but with array objects it displays
#half of the infomation like numpy.ndarray
# After getting numpy.ndarray the user can extract much of the knowledge with .dtype
# .dtype only works with numpy/array objects.
np.array(x5).dtype

dtype('O')