In [1]:
import numpy as np

# NumPy Indexing and Selection

discuss how to select elements or groups of elements from an array.

In [2]:
arr = np.arange(50,150)
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [3]:
print(arr[36])
print(arr[-13])

86
137


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
print(arr[10:50:2]) #arr[start:end:stepping(optional)]
print()
print(arr[10:])
print()
print(arr[:20])

[60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]

[ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [5]:
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [6]:
print(arr[0:5],arr[-21],sep='\n\n')

[50 51 52 53 54]

129


In [7]:
print(arr[::2],arr[::-1],arr[-1::-3],arr[:-21:-1],sep='\n\n')

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148]

[149 148 147 146 145 144 143 142 141 140 139 138 137 136 135 134 133 132
 131 130 129 128 127 126 125 124 123 122 121 120 119 118 117 116 115 114
 113 112 111 110 109 108 107 106 105 104 103 102 101 100  99  98  97  96
  95  94  93  92  91  90  89  88  87  86  85  84  83  82  81  80  79  78
  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63  62  61  60
  59  58  57  56  55  54  53  52  51  50]

[149 146 143 140 137 134 131 128 125 122 119 116 113 110 107 104 101  98
  95  92  89  86  83  80  77  74  71  68  65  62  59  56  53  50]

[149 148 147 146 145 144 143 142 141 140 139 138 137 136 135 134 133 132
 131 130]


## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [8]:
arr=np.arange(100,150)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [9]:
new = arr[:10]
new

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [10]:
new[5]=555

In [11]:
print(new)
arr

[100 101 102 103 104 555 106 107 108 109]


array([100, 101, 102, 103, 104, 555, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

Have you noticed the change in original list ?

In [12]:
# to avoid this 
arr = np.arange(100,150)
arr_new = np.copy(arr[0:10])
arr_new[:] = 555
print(arr_new)
arr

[555 555 555 555 555 555 555 555 555 555]


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

Data is not copied, it's a view of the original array! This avoids memory problems!

# Indexing a 2D array (matrices)

In [13]:
zxc = np.arange(1,31).reshape(5,6)
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [14]:
#14,28,6,24
zxc[[2,4,0,3],[1,3,5,5]]
#zxc[[row1,row2,row3,row4],[colum1,col2,col3,col4]]

array([14, 28,  6, 24])

In [15]:
zxc[2,2]

15

In [16]:
zxc[0,0]

1

In [17]:
#Exercise
abc=np.arange(200,250).reshape(10,5)
abc

array([[200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234],
       [235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244],
       [245, 246, 247, 248, 249]])

In [18]:
#Find 217,227,229,244,211,233,245,248,222,225,202
abc[[3,5,5,8,2,6,9,9,4,5,0],[2,2,4,4,1,3,0,3,2,0,2]]

array([217, 227, 229, 244, 211, 233, 245, 248, 222, 225, 202])

In [19]:
zxc[[1,4],:]

array([[ 7,  8,  9, 10, 11, 12],
       [25, 26, 27, 28, 29, 30]])

In [20]:
print(zxc[:,[4,2]],"\n")#only Columns


[[ 5  3]
 [11  9]
 [17 15]
 [23 21]
 [29 27]] 



In [21]:
zxc[4,:]

array([25, 26, 27, 28, 29, 30])

In [22]:
zxc[:,5]

array([ 6, 12, 18, 24, 30])

Fancy indexing allows the following

In [23]:
abc = np.arange(0,100).reshape(10,10)
abc

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
abc[[6,4,2,7]]    # extract rows only

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [25]:
abc[:,[6,4,2,7]]    # extract columns only

array([[ 6,  4,  2,  7],
       [16, 14, 12, 17],
       [26, 24, 22, 27],
       [36, 34, 32, 37],
       [46, 44, 42, 47],
       [56, 54, 52, 57],
       [66, 64, 62, 67],
       [76, 74, 72, 77],
       [86, 84, 82, 87],
       [96, 94, 92, 97]])

In [26]:
abc[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
abc[2:7,9]

array([29, 39, 49, 59, 69])

In [28]:
abc[9,:8]

array([90, 91, 92, 93, 94, 95, 96, 97])

In [29]:
abc[5,:6]

array([50, 51, 52, 53, 54, 55])

# Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.


In [30]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
arr[arr>=10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
arr[arr<=10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[(arr>=5) & (arr<=15)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arr[(arr>=5) | (arr<=15)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])