In [1]:
import numpy as np

# Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:


In [2]:
arr = np.arange(0,10)
arr1 = np.arange(0,11)
arr2 = np.arange(1,101)

In [3]:
print(arr,arr1,arr2,sep = "\n\n")

[0 1 2 3 4 5 6 7 8 9]

[ 0  1  2  3  4  5  6  7  8  9 10]

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [4]:
print(arr.shape,arr1.shape,arr2.shape,sep='  ')

(10,)  (11,)  (100,)


In [5]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr/arr

<ipython-input-7-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr1**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
x=np.arange(1,10)
y=np.array(10)
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
10


In [11]:
x+y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
asd=np.arange(0,10)
sun = np.append(asd,[55,66,77])
sun

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 55, 66, 77])

In [13]:
np.delete(sun,0)    #np.delete(<array_name>,<index of element>)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 55, 66, 77])

# Universal Array Functions

Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:


In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
np.log(arr)

<ipython-input-16-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
np.min(arr)

0

In [18]:
np.max(arr)

9

In [19]:
np.argmin(arr)  # telling about index

0

In [20]:
np.argmax(arr)  #  telling about index

9

In [21]:
np.mean(arr1)

5.0

In [22]:
np.median(arr1)

5.0

In [23]:
np.var(arr) #Variance

8.25

In [24]:
np.std(arr) #standard Deviation

2.8722813232690143