In [1]:
import numpy as np

In [2]:
print(np.arange(1,100))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [3]:
#1
print(np.arange(1,101).reshape(10,10))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [4]:
#2.a
print(np.array([[47,48,49],[57,58,59],[67,68,69]]).reshape(3,3))

[[47 48 49]
 [57 58 59]
 [67 68 69]]


In [5]:
#2.b
print(np.array([[40,41,42,43],[50,51,52,53],[60,61,62,63]]).reshape(3,4))

[[40 41 42 43]
 [50 51 52 53]
 [60 61 62 63]]


In [6]:
#2.c
print(np.array([np.arange(32,40),np.arange(42,50),np.arange(52,60),np.arange(62,70),np.arange(72,80)]).reshape(5,8))

[[32 33 34 35 36 37 38 39]
 [42 43 44 45 46 47 48 49]
 [52 53 54 55 56 57 58 59]
 [62 63 64 65 66 67 68 69]
 [72 73 74 75 76 77 78 79]]


In [7]:
#2.d
print(np.arange(20,60).reshape(4,10))

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


# Done!